
# python wrapper for package dna-compressor/internals/dna_encoding within overall package dnaencoding
# This is what you import to use the package.
# File is generated by gopy. Do not edit.
# gopy build -output=dna -vm=python3 dna-compressor/internals/dna_encoding

# the following is required to enable dlopen to open the _go.so file
import os,sys,inspect,collections
try:
	import collections.abc as _collections_abc
except ImportError:
	_collections_abc = collections

cwd = os.getcwd()
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
os.chdir(currentdir)
from . import _dnaencoding
from . import go

os.chdir(cwd)

# to use this code in your end-user python file, import it as follows:
# from dnaencoding import dnaencoding
# and then refer to everything using dnaencoding. prefix
# packages imported by this package listed below:




# ---- Types ---

# Python type for map map[rune]byte
class Map_rune_byte(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameter is a python list that we copy from
		"""
		self.index = 0
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_dnaencoding.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_dnaencoding.IncRef(self.handle)
		else:
			self.handle = _dnaencoding.Map_rune_byte_CTor()
			_dnaencoding.IncRef(self.handle)
			if len(args) > 0:
				if not isinstance(args[0], _collections_abc.Mapping):
					raise TypeError('Map_rune_byte.__init__ takes a mapping as argument')
				for k, v in args[0].items():
					_dnaencoding.Map_rune_byte_set(self.handle, k, v)
	def __del__(self):
		_dnaencoding.DecRef(self.handle)
	def __str__(self):
		s = 'dnaencoding.Map_rune_byte len: ' + str(len(self)) + ' handle: ' + str(self.handle) + ' {'
		if len(self) < 120:
			for k, v in self.items():
				s += str(k) + '=' + str(v) + ', '
		return s + '}'
	def __repr__(self):
		s = 'dnaencoding.Map_rune_byte({'
		for k, v in self.items():
			s += str(k) + '=' + str(v) + ', '
		return s + '})'
	def __len__(self):
		return _dnaencoding.Map_rune_byte_len(self.handle)
	def __getitem__(self, key):
		return _dnaencoding.Map_rune_byte_elem(self.handle, key)
	def __setitem__(self, key, value):
		_dnaencoding.Map_rune_byte_set(self.handle, key, value)
	def __delitem__(self, key):
		return _dnaencoding.Map_rune_byte_delete(self.handle, key)
	def keys(self):
		return go.Slice_rune(handle=_dnaencoding.Map_rune_byte_keys(self.handle))
	def values(self):
		vls = []
		kys = self.keys()
		for k in kys:
			vls.append(self[k])
		return vls
	def items(self):
		vls = []
		kys = self.keys()
		for k in kys:
			vls.append((k, self[k]))
		return vls
	def __iter__(self):
		return iter(self.items())
	def __contains__(self, key):
		return _dnaencoding.Map_rune_byte_contains(self.handle, key)


#---- Enums from Go (collections of consts with same type) ---


#---- Constants from Go: Python can only ask that you please don't change these! ---


# ---- Global Variables: can only use functions to access ---
def Encoding():
	"""
	Encoding Gets Go Variable: dnaencoding.Encoding
	
	"""
	return Map_rune_byte(handle=_dnaencoding.dnaencoding_Encoding())

def Set_Encoding(value):
	"""
	Set_Encoding Sets Go Variable: dnaencoding.Encoding
	
	"""
	if isinstance(value, go.GoClass):
		_dnaencoding.dnaencoding_Set_Encoding(value.handle)
	else:
		_dnaencoding.dnaencoding_Set_Encoding(value)



# ---- Interfaces ---


# ---- Structs ---


# ---- Slices ---


# ---- Maps ---


# ---- Constructors ---


# ---- Functions ---
def Encode(dna):
	"""Encode(str dna) []int, str
	
	Each DNA base is represented with 2 bits
	A/a = 00, C/c = 01, G/g = 10, T/t = 11
	"""
	return go.Slice_byte(handle=_dnaencoding.dnaencoding_Encode(dna))


